name: Single step workflow
on: workflow_dispatch
jobs:
  all_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: tests
        run: npm test
      - name: build
        run: npm run build
